<?php

/**
 * Generated by PHPUnit_SkeletonGenerator
 */
require_once '../testClass/addCartQtyClass.php';

class addCartQtyClassTest extends PHPUnit_Framework_TestCase {
    protected $object;

    protected function setUp() {
        $this->object = new addCartQtyClass;
    }

    protected function tearDown() {
        unset($this->object);
    }
    
    public function testEnoughStockToAddCorrect(){
        $this->assertTrue($this->object->testEnoughStockToAdd(2));
        $this->assertTrue($this->object->testEnoughStockToAdd(1));
        $this->assertFalse($this->object->testEnoughStockToAdd(0));
    }

    public function testAddQtyCorrect(){
        $this->assertTrue($this->object->testAddQty("1", 10));
        $this->assertFalse($this->object->testAddQty("2", 69));
    }
}
