<?php

require_once '../testclass/cartInitUnitTest.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-25 at 09:58:46.
 */
class cartInitUnitTestTest extends PHPUnit_Framework_TestCase {

    /**
     * @var cartInitUnitTest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new cartInitUnitTest;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * 
     * @runInSeparateProcess
     */
    public function testGetRedirect() {
        $res = $this->object->getRedirect();
    }

    //check initial session when no cart is added yet (empty sesson array)
    public function testValidateInitSessionIsEmptyTrue() {
        $result = $this->object->validateInitSessionIsEmpty();
        $this->assertEmpty($result);
    }

}
