<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-21 at 13:31:09.
 */
require_once '../testClass/cartPageClass.php';

class cartPageClassTest extends PHPUnit_Framework_TestCase {
    protected $object;

    protected function setUp() {
        $this->object = new cartPageClass;
    }

    protected function tearDown() {
        unset($this->object);
    }

    public function testAppendQueryCorrect(){
        $this->assertTrue($this->object->testAppendQuery("1", "2", "3"));
        $this->assertTrue($this->object->testAppendQuery("3", "2", "1"));
    }
    
    public function testFuncResponseStatusCorrect(){
        $this->assertTrue($this->object->testFuncResponseStatus("add", "success"));
        $this->assertTrue($this->object->testFuncResponseStatus("reduce", "success"));
        $this->assertTrue($this->object->testFuncResponseStatus("remove", "success"));
        $this->assertTrue($this->object->testFuncResponseStatus("add", "fail"));
        $this->assertTrue($this->object->testFuncResponseStatus("reduce", "fail"));
        $this->assertTrue($this->object->testFuncResponseStatus("remove", "fail"));
    }
    
    public function testFuncResponseMsgCorrect(){
        $this->assertTrue($this->object->testFuncResponseMsg("add", "success"));
        $this->assertTrue($this->object->testFuncResponseMsg("reduce", "success"));
        $this->assertTrue($this->object->testFuncResponseMsg("remove", "success"));
        $this->assertTrue($this->object->testFuncResponseMsg("add", "fail"));
        $this->assertTrue($this->object->testFuncResponseMsg("reduce", "fail"));
        $this->assertTrue($this->object->testFuncResponseMsg("remove", "fail"));
    }   
}
