<?php

require_once '../testclass/cartAddingUnitTest.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-22 at 16:44:55.
 */
class cartAddingUnitTestTest extends PHPUnit_Framework_TestCase {

    /**
     * @var cartSessionUnitTest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new cartAddingUnitTest;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    //adding cart array to session array
    public function testAddingNewItemTrue() {
        $addCart = array("isbn" => "9791296965391", "amt" => 20, "title" => "Book of Life", "pic" => "https://unsplash.com/photos/DCzpr09cTXY", "price" => 294);
        $result = $this->object->addingNewItem($addCart);
        $this->assertNotSame(0, count($result));
        $this->assertNotEmpty($result);
    }

    //false adding empty cart array to session array
    public function testAddingNewItemFalse() {
        $addCart = array();
        $result = $this->object->addingNewItem($addCart);
        $this->assertSame(0, count($result));
        $this->assertEmpty($result);
    }

    //test if session isbn == array isbn after pass from array to session
    public function testCheckAddedSessionISBN() {
        $addCart = array("isbn" => "9791296965391", "amt" => 20, "title" => "Book of Life", "pic" => "https://unsplash.com/photos/DCzpr09cTXY", "price" => 294);
        $arrayISBN = $addCart["isbn"];
        $sessionElement = $this->object->checkAddedSessionElement($addCart, "isbn");
        $this->assertSame($arrayISBN, $sessionElement);
    }

    //test if session amt == array amt after pass from array to session
    public function testCheckAddedSessionAmt() {
        $addCart = array("isbn" => "9791296965391", "amt" => 20, "title" => "Book of Life", "pic" => "https://unsplash.com/photos/DCzpr09cTXY", "price" => 294);
        $arrayAmt = $addCart["amt"];
        $sessionElement = $this->object->checkAddedSessionElement($addCart, "amt");
        $this->assertSame($arrayAmt, $sessionElement);
    }

    //test if session title == array title after pass from array to session
    public function testCheckAddedSessionTitle() {
        $addCart = array("isbn" => "9791296965391", "amt" => 20, "title" => "Book of Life", "pic" => "https://unsplash.com/photos/DCzpr09cTXY", "price" => 294);
        $arrayTitle = $addCart["title"];
        $sessionElement = $this->object->checkAddedSessionElement($addCart, "title");
        $this->assertSame($arrayTitle, $sessionElement);
    }

    //test if session url == array url after pass from array to session
    public function testCheckAddedSessionURL() {
        $addCart = array("isbn" => "9791296965391", "amt" => 20, "title" => "Book of Life", "pic" => "https://unsplash.com/photos/DCzpr09cTXY", "price" => 294);
        $arrayURL = $addCart["pic"];
        $sessionElement = $this->object->checkAddedSessionElement($addCart, "pic");
        $this->assertSame($arrayURL, $sessionElement);
    }

    //test if session url == array url after pass from array to session
    public function testCheckAddedSessionprice() {
        $addCart = array("isbn" => "9791296965391", "amt" => 20, "title" => "Book of Life", "pic" => "https://unsplash.com/photos/DCzpr09cTXY", "price" => 294);
        $arrayPrice = $addCart["price"];
        $sessionElement = $this->object->checkAddedSessionElement($addCart, "price");
        $this->assertSame($arrayPrice, $sessionElement);
    }

}
