<?php

require_once '../testclass/redirectUnitTest.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-28 at 06:34:38.
 */
class redirectUnitTestTest extends PHPUnit_Framework_TestCase {

    /**
     * @var redirectUnitTest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new redirectUnitTest;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    //test when xampp apache on
    public function testRedirectAboutStoryOK() {
        $result = $this->object->redirect200();
        $url = get_headers('http://localhost/Group11-BookStore/about.php#story');
        $this->assertSame($result, $url[0]);
    }

    public function testRedirectContactTalkOK() {
        $result = $this->object->redirect200();
        $url = get_headers('http://localhost/Group11-BookStore/contact.php#talk-us');
        $this->assertSame($result, $url[0]);
    }

    public function testRedirectContactMapOK() {
        $result = $this->object->redirect200();
        $url = get_headers('http://localhost/Group11-BookStore/contact.php#map');
        $this->assertSame($result, $url[0]);
    }

    public function testRedirectAboutStoryNotFound() {
        $result = $this->object->redirect404();
        $url = get_headers('http://localhost/Group11-BookStore/about.php#story');
        $this->assertNotSame($result, $url[0]);
    }

    public function testRedirectContactTalkNotFound() {
        $result = $this->object->redirect404();
        $url = get_headers('http://localhost/Group11-BookStore/contact.php#talk-us');
        $this->assertNotSame($result, $url[0]);
    }

    public function testRedirectCContactMapNotFound() {
        $result = $this->object->redirect404();
        $url = get_headers('http://localhost/Group11-BookStore/contact.php#map');
        $this->assertNotSame($result, $url[0]);
    }
}
