<?php

/**
 * Generated by PHPUnit_SkeletonGenerator
 */
require_once '../testClass/removeItemCartClass.php';

class removeItemCartClassTest extends PHPUnit_Framework_TestCase {

    protected $object;

    protected function setUp() {
        $this->object = new removeItemCartClass;
    }

    protected function tearDown() {
        unset($this->object);
    }
    
    public function testRemoveItemCorrect(){
       $this->assertTrue($this->object->testRemoveItem("1"));
       $this->assertTrue($this->object->testRemoveItem("2"));
   }
    
}
