<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-07-12 at 10:04:33.
 */
require_once '../test/addstock_stocklevels_integration_test.php';
class AddstockStocklevelsIntegrationTest extends PHPUnit_Framework_TestCase {

    protected $object;

    protected function setUp() {
        $this->object = new AddstockStocklevelsIntegration;
    }

    protected function tearDown() {
        unset($this->object);
    }

    public function test_addStockStockLevelsSearch_integrationTest() {
        $result = $this->object->performTest('9791256123789', 'Test Book Integration Testing', 'lukazio', date('Y-m-d'), 'for integration testing', '', 69, 420, 10, 'integration');
        $this->assertTrue($result);
    }

}
