<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-07-02 at 07:16:23.
 */
require_once '../test/book_info_addcart_test.php';
class BookInfoCartTest extends PHPUnit_Framework_TestCase {

    protected $object;

    protected function setUp() {
        $this->object = new BookInfoCart;
    }
    
    protected function tearDown() {
        unset($this->object);
    }
    
    public function testAdd1Time() {
        $result = $this->object->add1Time(5, 50);   // Add 5 books each cost 50, 1 time
        $this->assertTrue($result); // Expected totals: quantity 5, price 250
    }
    public function testAddNTimes() {
        $result = $this->object->addNTimes(2, 10, 100); // Add 2 books each cost 10, 100 times
        $this->assertTrue($result); // Expected totals: quantity 200, price 2000
    }
}
