<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-07-01 at 08:04:06.
 */
require_once '../test/isbn_test.php';
class IsbnTest extends PHPUnit_Framework_TestCase {

    protected $object;

    protected function setUp() {
        $this->object = new Isbn;
    }

    protected function tearDown() {
        unset($this->object);
    }

    public function testCheckISBN1() {
        $result = $this->object->checkISBN('9797734567895');    // Random valid ISBN
        $this->assertTrue($result);
    }
    public function testCheckISBN2() {
        $result = $this->object->checkISBN('979773456789');    // Missing 1 digit
        $this->assertFalse($result);
    }
    public function testCheckISBN3() {
        $result = $this->object->checkISBN('97977345678969');    // Extra 1 digit
        $this->assertFalse($result);
    }
    public function testCheckISBN4() {
        $result = $this->object->checkISBN('9781234567890');    // Valid 978
        $this->assertTrue($result);
    }
    public function testCheckISBN5() {
        $result = $this->object->checkISBN('9731234567890');    // 97 followed by a number not 8 or 9
        $this->assertFalse($result);
    }
    public function testCheckISBN6() {
        $result = $this->object->checkISBN('9881234567890');    // Doesn't start with "97"
        $this->assertFalse($result);
    }

}
