<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-23 at 11:17:02.
 */
require_once '../test/response_test.php';
class ResponseTest extends PHPUnit_Framework_TestCase {

    protected $object;

    protected function setUp() {
        $this->object = new Response;
    }

    protected function tearDown() {
        unset($this->object);
    }

    public function testBookInfoResponseCode() {    // Test for 200 OK
        $result = $this->object->checkOK('http://localhost/agile-project-group11-bookstore/book_info.php');
        $this->assertTrue($result);
    }
    public function testAddStockResponseCode() {    // Test for 200 OK
        $result = $this->object->checkOK('http://localhost/agile-project-group11-bookstore/add_stock.php');
        $this->assertTrue($result);
    }
    public function testStockLevelsResponseCode() { // Test for 200 OK
        $result = $this->object->checkOK('http://localhost/agile-project-group11-bookstore/stock_levels.php');
        $this->assertTrue($result);
    }
    public function testOrderHistoryResponseCode() { // Test for 200 OK
        $result = $this->object->checkOK('http://localhost/agile-project-group11-bookstore/order_history.php');
        $this->assertTrue($result);
    }
    public function testAddStockActionResponseCode() { // Test for 302 Found
        $result = $this->object->checkFound('http://localhost/agile-project-group11-bookstore/action/add_stock_action.php');
        $this->assertTrue($result);
    }
    public function testBookInfoActionResponseCode() { // Test for 302 Found
        $result = $this->object->checkFound('http://localhost/agile-project-group11-bookstore/action/book_info_action.php');
        $this->assertTrue($result);
    }
    public function testDeleteBookActionResponseCode() { // Test for 302 Found
        $result = $this->object->checkFound('http://localhost/agile-project-group11-bookstore/action/delete_book_action.php');
        $this->assertTrue($result);
    }
    public function testLogoutActionResponseCode() { // Test for 302 Found
        $result = $this->object->checkFound('http://localhost/agile-project-group11-bookstore/action/logout_action.php');
        $this->assertTrue($result);
    }
    public function test404ResponseCode() {         // Test for 404 Not Found
        $result = $this->object->checkNotFound('http://localhost/agile-project-group11-bookstore/very_fake_page.php');
        $this->assertTrue($result);
    }

}
