<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-07-07 at 09:19:42.
 */
require_once '../test/search_test.php';
class SearchTest extends PHPUnit_Framework_TestCase {

    protected $object;

    protected function setUp() {
        $this->object = new Search;
    }

    protected function tearDown() {
        unset($this->object);
    }
    
    public function testSearchBook1() {
        $result = $this->object->searchBook('granblue');    // Search for existing real book
        $this->assertTrue($result);
    }
    public function testSearchBook2() {
        $result = $this->object->searchBook('');    // Search all books with empty string, will always return true
        $this->assertTrue($result);
    }
    public function testSearchBook3() {
        $result = $this->object->searchBook('non existent book');    // Search for non-existent book
        $this->assertFalse($result);
    }

}
