<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-15 at 09:36:12.
 */

require_once '../test/testing.php';
class TestPasswordTest extends PHPUnit_Framework_TestCase {

    /**
     * @var TestPassword
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new TestPassword;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers TestPassword::checkPassword
     * @todo   Implement testCheckPassword().
     */
    public function testCheckPassword() {
        $this->assertTrue($this->object->checkPassword('Vincent?123'));
    }
}
